---
- name: Create Gitea container
  docker_container:
    name: "{{ gitea_name }}"
    image: "{{ gitea_image }}"
    pull: yes
    restart_policy: "unless-stopped"
    recreate: true
    networks:
      - name: "{{ network }}"
    env: "{{ gitea_env }}"
    volumes: "{{ gitea_volumes }}"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.gitea-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.gitea.entrypoints: "http"
      traefik.http.routers.gitea.rule: "Host(`{{ gitea_name }}.{{ domain }}`)"
      traefik.http.routers.gitea.middlewares: "gitea-https-redirect"
      traefik.http.routers.gitea-secure.entrypoints: "https"
      traefik.http.routers.gitea-secure.rule: "Host(`{{ gitea_name }}.{{ domain }}`)"
      traefik.http.routers.gitea-secure.tls: "true"
      traefik.http.routers.gitea-secure.service: "{{ gitea_name }}"
      traefik.http.services.gitea.loadbalancer.server.port: "{{ gitea_port }}"
      traefik.docker.network: "{{ network }}"
