---
- name: Create Redis container
  docker_container:
    name: "{{ redis_name }}"
    image: "{{ redis_image }}"
    pull: yes
    restart_policy: "unless-stopped"
    recreate: true
    network_mode: bridge
    exposed_ports:
      - 6379
    published_ports:
      - "{{ redis_port }}:6379"
    env: "{{ redis_env }}"

- name: Wait for Redis to be started
  wait_for:
    host: "localhost"
    port: "{{ redis_port }}"
    state: started
    delay: 5
    connect_timeout: 15
    timeout: 30
