---
pgadmin_name: "pgadmin"
pgadmin_home: "/opt/{{ pgadmin_name }}"
pgadmin_port: "80"
pgadmin_image: "dpage/pgadmin4:latest"
# Warning: pgAdmin runs as the pgadmin user (UID: 5050) in the pgadmin group (GID: 5050) in the container.
# You must ensure that all files are readable, and where necessary (e.g. the working/session directory)
# writeable for this user on the host machine. For example:
# sudo chown -R 5050:5050 <host_directory>
pgadmin_directories:
  - path: "{{ pgadmin_home }}/"
    owner: "5050"
    group: "5050"
pgadmin_volumes:
  - "{{ pgadmin_home }}:/var/lib/pgadmin"
pgadmin_env:
  PGADMIN_DEFAULT_EMAIL: "{{ email }}"
  PGADMIN_DEFAULT_PASSWORD: "{{ password }}"
  PGADMIN_LISTEN_PORT: "{{ pgadmin_port }}"
