---
docker_volume_backup_name: "docker-volume-backup"
docker_volume_backup_image: "offen/docker-volume-backup:latest"
docker_volume_backup_volumes:
  - "{{ postgres_home }}/backups:/backup/postgres:ro"
  - "/var/run/docker.sock:/var/run/docker.sock:ro"
docker_volume_backup_env:
  WEBDAV_URL_INSECURE: "true"
  WEBDAV_URL: "{{ webdav_url }}"
  WEBDAV_PATH: "{{ webdav_path }}"
  WEBDAV_USERNAME: "{{ webdav_user }}"
  WEBDAV_PASSWORD: "{{ webdav_password }}"
  BACKUP_FILENAME: "backup-%Y-%m-%dT%H-%M-%S.tar.gz"
  BACKUP_PRUNING_PREFIX: "backup-"
  BACKUP_RETENTION_DAYS: "7"
  NOTIFICATION_URLS: "telegram://{{ docker_volume_backup_bot_token }}@telegram?chats={{ telegram_chat_id }}"
  NOTIFICATION_LEVEL: "info"
