---
- name: Create Planka container
  docker_container:
    name: "{{ planka_name }}"
    image: "{{ planka_image }}"
    pull: yes
    restart_policy: "unless-stopped"
    recreate: true
    command: >
      bash -c
        "for i in `seq 1 30`; do
          ./start.sh &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 seconds...\";
          sleep 5;
        done; (exit $$s)"
    networks:
      - name: "{{ network }}"
    env:
      BASE_URL: "https://{{ planka_name }}.{{ domain }}"
      TRUST_PROXY: "0"
      DATABASE_URL: "{{ planka_db_url }}"
      SECRET_KEY: "{{ planka_secret }}"
    volumes: "{{ planka_volumes }}"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.planka-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.planka.entrypoints: "http"
      traefik.http.routers.planka.rule: "Host(`{{ planka_name }}.{{ domain }}`)"
      traefik.http.routers.planka.middlewares: "planka-https-redirect"
      traefik.http.routers.planka-secure.entrypoints: "https"
      traefik.http.routers.planka-secure.rule: "Host(`{{ planka_name }}.{{ domain }}`)"
      traefik.http.routers.planka-secure.tls: "true"
      traefik.http.routers.planka-secure.service: "{{ planka_name }}"
      traefik.http.services.planka.loadbalancer.server.port: "{{ planka_port }}"
      traefik.docker.network: "{{ network }}"
