---
planka_name: "planka"
planka_home: "/opt/{{ planka_name }}"
planka_port: "1337"
planka_image: "ghcr.io/plankanban/planka:latest"
planka_directories:
  - path: "{{ planka_home }}/"
    owner: "{{ user }}"
    group: "{{ group }}"
  - path: "{{ planka_home }}/avatars"
    owner: "{{ user }}"
    group: "{{ group }}"
  - path: "{{ planka_home }}/backgrounds"
    owner: "{{ user }}"
    group: "{{ group }}"
  - path: "{{ planka_home }}/attachments"
    owner: "{{ user }}"
    group: "{{ group }}"
planka_volumes:
  - "{{ planka_home }}/avatars:/app/public/user-avatars"
  - "{{ planka_home }}/backgrounds:/app/public/project-background-images"
  - "{{ planka_home }}/attachments:/app/private/attachments"

