---
- name: Create postgres container
  community.docker.docker_container:
    name: "{{ postgres_name }}"
    image: "{{ postgres_image }}"
    pull: yes
    restart_policy: "unless-stopped"
    recreate: true
    network_mode: bridge
    exposed_ports:
      - 5432
    published_ports:
      - "{{ postgres_port }}:5432"
    user: "root"
    env: "{{ postgres_env }}"
    volumes: "{{ postgres_volumes }}"
    labels:
      docker-volume-backup.archive-pre: "/bin/sh -c 'pg_dumpall > /tmp/backups/dump.sql'"

- name: Wait for postgres to be started
  wait_for:
    host: "localhost"
    port: "{{ postgres_port }}"
    state: started
    delay: 5
    connect_timeout: 15
    timeout: 30



