---
- name: Create Grafana container
  docker_container:
    name: "{{ grafana_name }}"
    image: "{{ grafana_image }}"
    pull: yes
    restart_policy: "unless-stopped"
    recreate: true
    user: "root"
    networks:
      - name: "{{ network }}"
    env: "{{ grafana_env }}"
    volumes: "{{ grafana_volumes }}"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.grafana.entrypoints: "http"
      traefik.http.routers.grafana.rule: "Host(`{{ grafana_name }}.{{ domain }}`)"
      traefik.http.routers.grafana.middlewares: "grafana-https-redirect"
      traefik.http.routers.grafana-secure.entrypoints: "https"
      traefik.http.routers.grafana-secure.rule: "Host(`{{ grafana_name }}.{{ domain }}`)"
      traefik.http.routers.grafana-secure.tls: "true"
      traefik.http.routers.grafana-secure.service: "{{ grafana_name }}"
      traefik.http.services.grafana.loadbalancer.server.port: "{{ grafana_port }}"
      traefik.docker.network: "{{ network }}"
