---
- name: Create node-exporter container
  docker_container:
    name: "{{ node_exporter_name }}"
    image: "{{ node_exporter_image }}"
    pull: yes
    restart_policy: "unless-stopped"
    recreate: true
    exposed_ports:
      - "{{ node_exporter_port }}"
    published_ports:
      - "{{ node_exporter_port }}:9100"
    volumes: "{{ node_exporter_volumes }}"
    command: "{{ node_exporter_command }}"
