---
pihole_name: "pihole"
pihole_home: "/opt/{{ pihole_name }}"
pihole_port: "80"
pihole_image: "pihole/pihole:latest"
pihole_directories:
  - path: "{{ pihole_home }}/"
    owner: "{{ user }}"
    group: "{{ group }}"
  - path: "{{ pihole_home }}/pihole"
    owner: "{{ user }}"
    group: "{{ group }}"
  - path: "{{ pihole_home }}/dnsmasq.d"
    owner: "{{ user }}"
    group: "{{ group }}"
pihole_volumes:
  - "{{ pihole_home }}/pihole:/etc/pihole/"
  - "{{ pihole_home }}/dnsmasq.d:/etc/dnsmasq.d/"
pihole_env:
  TZ: "{{ timezone }}"
  WEBPASSWORD: "{{ password }}"
  DNSSEC: "false"
  VIRTUAL_HOST: "{{ pihole_name }}.{{ domain }}"
  WEBTHEME: "default-dark"
