---
prometheus_name: "prometheus"
prometheus_home: "/opt/{{ prometheus_name }}"
prometheus_image: "prom/prometheus:latest"
prometheus_directories:
  - path: "{{ prometheus_home }}/"
    owner: "{{ user }}"
    group: "{{ group }}"
  - path: "{{ prometheus_home }}/data"
    owner: "{{ user }}"
    group: "{{ group }}"
  - path: "{{ prometheus_home }}/config"
    owner: "{{ user }}"
    group: "{{ group }}"
  - path: "{{ prometheus_home }}/config/rules"
    owner: "{{ user }}"
    group: "{{ group }}"
prometheus_volumes:
  - "{{ prometheus_home }}/config:/etc/prometheus/"
  - "{{ prometheus_home }}/data:/var/lib/prometheus"
prometheus_env:
  TZ: "{{ timezone }}"
prometheus_command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/var/lib/prometheus"
      - "--storage.tsdb.retention.time=7d"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
