---
# Main
timezone: "Europe/Moscow"
# Portainer
portainer_host: "franky"
# Networks
network: "proxy"
dns_primary: "1.1.1.1"
dns_secondary: "1.0.0.1"
# PostgreSQL
postgres_name: postgres
postgres_home: "/opt/{{ postgres_name }}"
postgres_port: 5432
postgres_host: "chopper"
# pgAdmin
pgadmin_host: "franky"
# Redis
redis_port: 6379
redis_host: "chopper"
# Pihole
pihole_host: "franky"
# MinIO
minio_name: "minio"
minio_port: 9000
minio_host: "franky"
# Planka
planka_name: "planka"
planka_db: "planka"
planka_db_user: "planka"
planka_host: "franky"
# Gitea
gitea_name: "gitea"
gitea_db: "gitea"
gitea_db_user: "gitea"
gitea_host: "franky"
# Penpot
penpot_name: "penpot"
penpot_db: "penpot"
penpot_db_user: "penpot"
penpot_aws_bucket: "penpot"
penpot_host: "franky"
# AlertManager
alertmanager_host: "jinbe"
# cAdvisor
cadvisor_port: 9092
# node-exporter
node_exporter_port: 9091
# Prometheus
prometheus_host: "jinbe"
prometheus_port: "9090"
# Grafana
grafana_name: "grafana"
grafana_host: "franky"
# Uptime Kuma
uptime_kuma_host: "franky"
