---
- name: Create Pi-hole container
  docker_container:
    name: "{{ pihole_name }}"
    image: "{{ pihole_image }}"
    pull: yes
    restart_policy: "unless-stopped"
    recreate: true
    networks:
      - name: "{{ network }}"
    dns_servers:
      - 127.0.0.1
      - "{{ dns_primary }}"
      - "{{ dns_secondary }}"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    capabilities:
      - NET_ADMIN
    env: "{{ pihole_env }}"
    volumes: "{{ pihole_volumes }}"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.pihole-https-redirect.redirectscheme.scheme: "https"
      traefik.http.middlewares.pihole-https-redirect.redirectscheme.permanent: "true"
      traefik.http.routers.pihole.entrypoints: "http"
      traefik.http.routers.pihole.rule: "Host(`{{ pihole_name }}.{{ domain }}`)"
      traefik.http.routers.pihole.middlewares: "pihole-https-redirect"
      traefik.http.routers.pihole-secure.entrypoints: "https"
      traefik.http.routers.pihole-secure.rule: "Host(`{{ pihole_name }}.{{ domain }}`)"
      traefik.http.routers.pihole-secure.tls: "true"
      traefik.http.routers.pihole-secure.service: "{{ pihole_name }}"
      traefik.http.services.pihole.loadbalancer.server.port: "{{ pihole_port }}"
      traefik.docker.network: "{{ network }}"
