---
- name: Set DATABASE_URI fact
  set_fact:
    penpot_db_url: "postgresql://{{ hostvars[postgres_host]['ansible_default_ipv4']['address'] }}:{{ postgres_port }}/{{ penpot_db }}"

- name: Set REDIS_URI fact
  set_fact:
    penpot_redis_url: "redis://{{ hostvars[redis_host]['ansible_default_ipv4']['address'] }}:{{ redis_port }}/0"

- name: Set MINIO_URI fact
  set_fact:
    penpot_aws_endpoint: "http://{{ hostvars[minio_host]['ansible_default_ipv4']['address'] }}:{{ minio_port }}/"

- name: Create url safe token string
  shell:
    cmd: "python3 -c 'import secrets; print(secrets.token_urlsafe(64))'"
  register: penpot_secret_str

- name: Set SECRET_KEY fact
  set_fact:
    penpot_secret: "{{ penpot_secret_str.stdout }}"


