---
minio_home: "/opt/{{ minio_name }}"
minio_console: "9001"
minio_image: "minio/minio:latest"
minio_directories:
  - path: "{{ minio_home }}/"
    owner: "{{ user }}"
    group: "{{ group }}"
minio_volumes:
  - "{{ minio_home }}:/mnt/data"
minio_env:
  MINIO_ROOT_USER: "{{ user }}"
  MINIO_ROOT_PASSWORD: "{{ password }}"
  MINIO_PROMETHEUS_AUTH_TYPE: "public"
  MINIO_PROMETHEUS_URL: "http://{{ hostvars[prometheus_host]['ansible_default_ipv4']['address'] }}:{{ prometheus_port }}/"
  MINIO_PROMETHEUS_JOB_ID: "{{ minio_name }}"
