---
- name: Create Portainer Agent container
  docker_container:
    name: "{{ portainer_agent_name }}"
    image: "{{ portainer_agent_image }}"
    pull: yes
    restart_policy: "unless-stopped"
    recreate: true
    exposed_ports:
      - "{{ portainer_agent_port }}"
    published_ports:
      - "{{ portainer_agent_port }}:{{ portainer_agent_port }}"
    volumes: "{{ portainer_agent_volumes }}"
