---
- name: Create Portainer container
  docker_container:
    name: "{{ portainer_name }}"
    image: "{{ portainer_image }}"
    pull: yes
    restart_policy: "unless-stopped"
    recreate: true
    networks:
      - name: "{{ network }}"
    exposed_ports:
      - "{{ portainer_port }}"
    volumes: "{{ portainer_volumes }}"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.portainer.entrypoints: "http"
      traefik.http.routers.portainer.rule: "Host(`{{ portainer_name }}.{{ domain }}`)"
      traefik.http.routers.portainer.middlewares: "portainer-https-redirect"
      traefik.http.routers.portainer-secure.entrypoints: "https"
      traefik.http.routers.portainer-secure.rule: "Host(`{{ portainer_name }}.{{ domain }}`)"
      traefik.http.routers.portainer-secure.tls: "true"
      traefik.http.routers.portainer-secure.service: "{{ portainer_name }}"
      traefik.http.services.portainer.loadbalancer.server.port: "{{ portainer_port }}"
      traefik.docker.network: "{{ network }}"
