---
- name: Create Prometheus container
  docker_container:
    name: "{{ prometheus_name }}"
    image: "{{ prometheus_image }}"
    pull: yes
    restart_policy: "unless-stopped"
    recreate: true
    user: "root"
    exposed_ports:
      - "{{ prometheus_port }}"
    published_ports:
      - "{{ prometheus_port }}:{{ prometheus_port }}"
    volumes: "{{ prometheus_volumes }}"
    command: "{{ prometheus_command }}"

