---
node_exporter_name: "node-exporter"
node_exporter_image: "prom/node-exporter:latest"
node_exporter_volumes:
  - "/proc:/host/proc:ro"
  - "/sys:/host/sys:ro"
  - "/:/rootfs:ro"
node_exporter_command:
  - "--path.procfs=/host/proc"
  - "--path.rootfs=/rootfs"
  - "--path.sysfs=/host/sys"
  - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
