---
postgres_image: postgres:15
postgres_user_name: root
postgres_user_password: root
postgres_db: root
postgres_initdb:
postgres_directories:
  - path: "{{ postgres_home }}/"
    owner: "{{ user }}"
  - path: "{{ postgres_home }}/data"
    owner: "{{ user }}"
  - path: "{{ postgres_home }}/docker-entrypoint-initdb.d"
    owner: "{{ user }}"
  - path: "{{ postgres_home }}/backups"
    owner: "{{ user }}"
postgres_volumes:
  - "{{ postgres_home }}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
  - "{{ postgres_home }}/data:/var/lib/postgresql/data"
  - "{{ postgres_home }}/backups:/tmp/backups"
postgres_env:
  POSTGRES_USER: "{{ postgres_user_name }}"
  POSTGRES_PASSWORD: "{{ postgres_user_password }}"
  POSTGRES_DB: "{{ postgres_db }}"

