---
traefik_name: "traefik"
traefik_home: "/opt/{{ traefik_name }}"
traefik_image: "traefik:latest"
traefik_directories:
  - path: "{{ traefik_home }}/"
    owner: "{{ user }}"
    group: "{{ group }}"
traefik_volumes:
  - "/etc/localtime:/etc/localtime:ro"
  - "/var/run/docker.sock:/var/run/docker.sock:ro"
  - "{{ traefik_home }}/acme.json:/acme.json"
  - "{{ traefik_home }}/traefik.yml:/traefik.yml:ro"
  - "{{ traefik_home }}/config.yml:/config.yml:ro"
traefik_env:
  CF_API_EMAIL: "{{ cloudflare_email }}"
  CF_API_KEY: "{{ cloudflare_token }}"
