---
gitea_name: "gitea"
gitea_home: "/opt/{{ gitea_name }}"
gitea_port: "3000"
gitea_image: "gitea/gitea:latest"
gitea_directories:
  - path: "{{ gitea_home }}/"
    owner: "{{ user }}"
    group: "{{ group }}"
  - path: "{{ gitea_home }}/data"
    owner: "{{ user }}"
    group: "{{ group }}"
gitea_volumes:
  - "/etc/timezone:/etc/timezone:ro"
  - "/etc/localtime:/etc/localtime:ro"
  - "{{ gitea_home }}/data:/data"
gitea_env:
  USER_UID: "1000"
  USER_GID: "1000"
  GITEA__database__DB_TYPE: "postgres"
  GITEA__database__HOST: "{{ hostvars[postgres_host]['ansible_default_ipv4']['address'] }}:{{ postgres_port }}"
  GITEA__database__NAME: "{{ gitea_db }}"
  GITEA__database__USER: "{{ gitea_db_user }}"
  GITEA__database__PASSWD: "{{ password }}"
