---
- name: Create MiniIO container
  docker_container:
    name: "{{ minio_name }}"
    image: "{{ minio_image }}"
    pull: yes
    restart_policy: "unless-stopped"
    recreate: true
    command: minio server /mnt/data --console-address ":{{ minio_console }}"
    networks:
      - name: "{{ network }}"
    env: "{{ minio_env }}"
    volumes: "{{ minio_volumes }}"
    exposed_ports:
      - "{{ minio_console }}"
      - "{{ minio_port }}"
    published_ports:
      - "{{ minio_console }}:9001"
      - "{{ minio_port }}:9000"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.minio-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.minio.entrypoints: "http"
      traefik.http.routers.minio.rule: "Host(`{{ minio_name }}.{{ domain }}`)"
      traefik.http.routers.minio.middlewares: "minio-https-redirect"
      traefik.http.routers.minio-secure.entrypoints: "https"
      traefik.http.routers.minio-secure.rule: "Host(`{{ minio_name }}.{{ domain }}`)"
      traefik.http.routers.minio-secure.tls: "true"
      traefik.http.routers.minio-secure.service: "{{ minio_name }}"
      traefik.http.services.minio.loadbalancer.server.port: "{{ minio_console }}"
      traefik.docker.network: "{{ network }}"
